# Generated by Django 4.0.5 on 2022-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_carmodels_condintions_partbrend_partitemnooem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condintions',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
