# Generated by Django 4.0.5 on 2022-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_condintions_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partbrend',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
