# Generated by Django 4.0.5 on 2022-11-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_partbrend_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partbrend',
            name='oem',
        ),
        migrations.AddField(
            model_name='partbrend',
            name='history',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
