# Generated by Django 4.0.5 on 2022-11-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_remove_partbrend_oem_partbrend_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemnooem',
            name='analogs',
            field=models.ManyToManyField(blank=True, to='first.partitemoem'),
        ),
        migrations.AlterField(
            model_name='partitemoem',
            name='analogs',
            field=models.ManyToManyField(blank=True, to='first.partitemnooem'),
        ),
    ]
