# Generated by Django 4.0.5 on 2022-11-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_alter_partitemnooem_analogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitemnooem',
            name='quant_reserved',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='partitemoem',
            name='quant_reserved',
            field=models.IntegerField(blank=True),
        ),
    ]
