# Generated by Django 4.0.5 on 2022-11-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_remove_partitemnooem_quant_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitemnooem',
            name='analogs',
        ),
        migrations.RemoveField(
            model_name='partitemnooem',
            name='app',
        ),
        migrations.RemoveField(
            model_name='partitemnooem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='partitemnooem',
            name='cond',
        ),
        migrations.RemoveField(
            model_name='partitemoem',
            name='analogs',
        ),
        migrations.RemoveField(
            model_name='partitemoem',
            name='app',
        ),
        migrations.RemoveField(
            model_name='partitemoem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='partitemoem',
            name='cond',
        ),
        migrations.DeleteModel(
            name='CarBrends',
        ),
        migrations.DeleteModel(
            name='CarModels',
        ),
        migrations.DeleteModel(
            name='Condintions',
        ),
        migrations.DeleteModel(
            name='PartBrend',
        ),
        migrations.DeleteModel(
            name='PartItemNoOem',
        ),
        migrations.DeleteModel(
            name='PartItemOem',
        ),
    ]
