# Generated by Django 4.0.5 on 2022-11-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_remove_partitemnooem_analogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('desc', models.TextField(blank=True, max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='PartBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('history', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('quantaty', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.partbrend')),
                ('cond', models.ManyToManyField(to='first.conditions')),
            ],
        ),
    ]
