# Generated by Django 4.0.5 on 2022-11-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_alter_carbrands_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='app',
            field=models.ManyToManyField(to='first.carmodels'),
        ),
    ]
