# Generated by Django 4.0.5 on 2022-11-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_partitem_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitem',
            name='app',
        ),
    ]
