# Generated by Django 4.0.5 on 2022-11-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_partitem_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='analogs',
            field=models.ManyToManyField(to='first.partitem'),
        ),
    ]
