# Generated by Django 4.0.5 on 2022-11-03 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0019_partitem_analogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=35)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('desc', models.CharField(max_length=35)),
            ],
        ),
        migrations.AddField(
            model_name='partitem',
            name='category',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='first.catalog'),
        ),
    ]
