# Generated by Django 4.0.5 on 2022-11-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_catalog_partitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='first.catalog'),
        ),
    ]
