# Generated by Django 4.0.5 on 2022-11-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0023_alter_partitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='desc',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
