# Generated by Django 4.0.5 on 2022-11-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_alter_catalog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='analogs',
            field=models.ManyToManyField(blank=True, to='first.partitem'),
        ),
    ]
