# Generated by Django 4.0.5 on 2022-11-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_alter_partitem_analogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='oem',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
