# Generated by Django 4.0.5 on 2022-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_alter_partitem_oem'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
