# Generated by Django 4.0.5 on 2022-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_partitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrands',
            name='models',
            field=models.ManyToManyField(blank=True, to='first.carmodels'),
        ),
    ]
