# Generated by Django 4.0.5 on 2022-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_alter_partitem_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='cond',
            field=models.ManyToManyField(blank=True, to='first.conditions'),
        ),
    ]
