# Generated by Django 4.0.5 on 2022-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0031_alter_partitem_cond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='oem',
            field=models.CharField(max_length=25),
        ),
    ]
