# Generated by Django 4.0.5 on 2022-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_partitem_oemin_alter_carbrands_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrands',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
