# Generated by Django 4.0.5 on 2022-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0036_alter_carmodels_name_alter_partitem_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitem',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
