# Generated by Django 4.0.5 on 2022-11-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0039_carmodels_featured_image_partbrand_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrands',
            options={'ordering': ['name'], 'verbose_name': 'Марки'},
        ),
    ]
