# Generated by Django 4.0.5 on 2022-11-17 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0041_contryes_partbrand_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitem',
            name='cond',
        ),
        migrations.AddField(
            model_name='partitem',
            name='cond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.conditions'),
        ),
    ]
