# Generated by Django 4.0.5 on 2022-11-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0042_remove_partitem_cond_partitem_cond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterModelOptions(
            name='carbrands',
            options={'ordering': ['name'], 'verbose_name': 'Марки', 'verbose_name_plural': 'Марки'},
        ),
        migrations.AlterModelOptions(
            name='partitem',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
