# Generated by Django 4.0.5 on 2022-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0043_remove_account_user_delete_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrands',
            options={'ordering': ['name'], 'verbose_name': 'Марки авто', 'verbose_name_plural': 'Марки авто'},
        ),
        migrations.AlterModelOptions(
            name='carmodels',
            options={'verbose_name': 'Модели авто', 'verbose_name_plural': 'Модели авто'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Каталог товаров', 'verbose_name_plural': 'Каталог товаров'},
        ),
        migrations.AlterModelOptions(
            name='conditions',
            options={'verbose_name': 'Состояние товара', 'verbose_name_plural': 'Состояния товара'},
        ),
        migrations.AlterModelOptions(
            name='contryes',
            options={'verbose_name': 'Страна Производителя', 'verbose_name_plural': 'Страны Производителей'},
        ),
        migrations.AlterModelOptions(
            name='partbrand',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='partbrand',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/PartBrands'),
        ),
    ]
