# Generated by Django 4.0.5 on 2022-11-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0045_alter_catalog_logo_alter_partbrand_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Категория товаров', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterField(
            model_name='carbrands',
            name='logo',
            field=models.ImageField(blank=True, upload_to='CarBrands'),
        ),
    ]
