# Generated by Django 4.0.5 on 2022-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0046_alter_catalog_options_alter_carbrands_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitem',
            name='img',
        ),
        migrations.AlterField(
            model_name='partitem',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Parts'),
        ),
    ]
