# Generated by Django 4.0.5 on 2022-12-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0048_remove_carmodels_logo_remove_partbrand_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='featured_image_2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Parts'),
        ),
        migrations.AddField(
            model_name='partitem',
            name='featured_image_3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Parts'),
        ),
    ]
