# Generated by Django 4.0.5 on 2022-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0049_partitem_featured_image_2_partitem_featured_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitem',
            name='featured_image_4',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Parts'),
        ),
    ]
